version: '3.8'

services:
  fastapi:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
    - 8000:8000
    environment:
      DEBUG: 1
      SECRET_KEY: 6a67rstg87fmm4-yrw-tydn=o^*n$k$ju&z09f*kdp#10c)#=d